services:
  db:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: dev
    ports:
      - "27017:27017"
    volumes:
      - ./devdb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: mongo
      DB_PASSWORD: mongo
      DB_NAME: dev
      ADMIN_PASSWORD: "00000000000000000000000000000000"
    ports:
      - "4000:3000"
    volumes:
      - ./api:/app/api
      - ./lexicon:/app/lexicon
      - ./services:/app/services
      - ./utils:/app/utils
      - ./main.ts:/app/main.ts
      - ./deno.json:/app/deno.json
      - ./deno.lock:/app/deno.lock
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./api
          action: sync+restart
          target: /app/api
        - path: ./lexicon
          action: sync+restart
          target: /app/lexicon
        - path: ./services
          action: sync+restart
          target: /app/services
        - path: ./utils
          action: sync+restart
          target: /app/utils
        - path: ./main.ts
          action: rebuild
          target: /app/main.ts
    restart: unless-stopped
