import { Server } from "@atp/xrpc-server";

import { AppContext } from "../context.ts";
import getAccountInfos from "./com/atproto/admin/getAccountInfos.ts";
import getSubjectStatus from "./com/atproto/admin/getSubjectStatus.ts";
import updateSubjectStatus from "./com/atproto/admin/updateSubjectStatus.ts";
import getPosts from "./so/sprk/feed/getPosts.ts";
import getProfile from "./so/sprk/actor/getProfile.ts";
import getAuthorFeed from "./so/sprk/feed/getAuthorFeed.ts";
import getPostThread from "./so/sprk/feed/getPostThread.ts";
import getCrosspostThread from "./so/sprk/feed/getCrosspostThread.ts";
import getActorLikes from "./so/sprk/feed/getActorLikes.ts";
import getActorReposts from "./so/sprk/feed/getActorReposts.ts";
import getAudios from "./so/sprk/sound/getAudios.ts";
import getAudioPosts from "./so/sprk/sound/getAudioPosts.ts";
import getFollows from "./so/sprk/graph/getFollows.ts";
import getFollowers from "./so/sprk/graph/getFollowers.ts";
import getKnownFollowers from "./so/sprk/graph/getKnownFollowers.ts";
import getBlocks from "./so/sprk/graph/getBlocks.ts";
import putPreferences from "./so/sprk/actor/putPreferences.ts";
import getPreferences from "./so/sprk/actor/getPreferences.ts";
import searchActors from "./so/sprk/actor/searchActors.ts";
import searchActorsTypeahead from "./so/sprk/actor/searchActorsTypeahead.ts";
import getRecord from "./com/atproto/repo/getRecord.ts";
import resolveHandle from "./com/atproto/identity/resolveHandle.ts";
import getStories from "./so/sprk/story/getStories.ts";
import getStoriesTimeline from "./so/sprk/story/getTimeline.ts";
import getProfiles from "./so/sprk/actor/getProfiles.ts";
import searchPosts from "./so/sprk/feed/searchPosts.ts";
import getActorAudios from "./so/sprk/sound/getActorAudios.ts";
import getTrendingAudios from "./so/sprk/sound/getTrendingAudios.ts";
import getSuggestedFeeds from "./so/sprk/feed/getSuggestedFeeds.ts";
import getTimeline from "./so/sprk/feed/getTimeline.ts";
import getFeed from "./so/sprk/feed/getFeed.ts";
import getFeedGenerator from "./so/sprk/feed/getFeedGenerator.ts";
import getFeedGenerators from "./so/sprk/feed/getFeedGenerators.ts";
import getServices from "./so/sprk/labeler/getServices.ts";
import listNotifications from "./so/sprk/notification/listNotifications.ts";
import getUnreadCount from "./so/sprk/notification/getUnreadCount.ts";
import updateSeen from "./so/sprk/notification/updateSeen.ts";
import registerPush from "./so/sprk/notification/registerPush.ts";
import unregisterPush from "./so/sprk/notification/unregisterPush.ts";

export default function (server: Server, ctx: AppContext) {
  getAccountInfos(server, ctx);
  getSubjectStatus(server, ctx);
  updateSubjectStatus(server, ctx);
  getPosts(server, ctx);
  getProfile(server, ctx);
  getProfiles(server, ctx);
  getAuthorFeed(server, ctx);
  getPostThread(server, ctx);
  getCrosspostThread(server, ctx);
  getActorLikes(server, ctx);
  getActorReposts(server, ctx);
  getAudios(server, ctx);
  getAudioPosts(server, ctx);
  getFollows(server, ctx);
  getFollowers(server, ctx);
  getKnownFollowers(server, ctx);
  getBlocks(server, ctx);
  putPreferences(server, ctx);
  getPreferences(server, ctx);
  searchActors(server, ctx);
  searchActorsTypeahead(server, ctx);
  getRecord(server, ctx);
  resolveHandle(server, ctx);
  getStories(server, ctx);
  getStoriesTimeline(server, ctx);
  searchPosts(server, ctx);
  getActorAudios(server, ctx);
  getTrendingAudios(server, ctx);
  getSuggestedFeeds(server, ctx);
  getTimeline(server, ctx);
  getFeed(server, ctx);
  getFeedGenerator(server, ctx);
  getFeedGenerators(server, ctx);
  getServices(server, ctx);
  listNotifications(server, ctx);
  getUnreadCount(server, ctx);
  updateSeen(server, ctx);
  registerPush(server, ctx);
  unregisterPush(server, ctx);
}
